<?php
/** @var array<string,mixed> $data @var array<string,mixed> $catchup */
if ( ! defined( 'ABSPATH' ) ) { exit; }
$items=(array)($data['items']??array());
?>
<section class="sun-center sun-center--intelligent" aria-labelledby="sun-center-title" data-sun-center>
<header class="sun-center__header"><div><h1 id="sun-center-title"><?php esc_html_e('Notifications','sabri-unified-notifications');?></h1><p><?php esc_html_e('Priority-aware, private and explainable notification center.','sabri-unified-notifications');?></p></div><div class="sun-center__actions"><a class="sun-button" href="<?php echo esc_url(home_url('/settings/notifications/'));?>">⚙ <?php esc_html_e('Settings','sabri-unified-notifications');?></a><button class="sun-button" type="button" data-sun-bulk-action="read"><?php esc_html_e('Mark all read','sabri-unified-notifications');?></button></div></header>
<div class="sun-catchup" data-sun-catchup><div><strong><?php esc_html_e('Catch-up','sabri-unified-notifications');?></strong><p data-sun-catchup-text><?php echo esc_html((string)($catchup['summary']??__('Your important updates will be summarized here.','sabri-unified-notifications')));?></p></div><button type="button" class="sun-button" data-sun-refresh-catchup><?php esc_html_e('Refresh summary','sabri-unified-notifications');?></button></div>
<form class="sun-search" role="search" data-sun-search-form><label class="screen-reader-text" for="sun-notification-search"><?php esc_html_e('Search notifications','sabri-unified-notifications');?></label><input id="sun-notification-search" type="search" placeholder="<?php esc_attr_e('Search notifications, sources or topics','sabri-unified-notifications');?>" data-sun-search-input><button class="sun-button" type="submit">🔎 <?php esc_html_e('Search','sabri-unified-notifications');?></button></form>
<nav class="sun-filters" aria-label="<?php esc_attr_e('Notification filters','sabri-unified-notifications');?>"><button type="button" data-sun-smart-filter="priority" aria-pressed="true"><?php esc_html_e('Priority','sabri-unified-notifications');?></button><button type="button" data-sun-filter="unread" aria-pressed="false"><?php esc_html_e('Unread','sabri-unified-notifications');?></button><button type="button" data-sun-smart-filter="pinned" aria-pressed="false"><?php esc_html_e('Pinned','sabri-unified-notifications');?></button><button type="button" data-sun-smart-filter="needs_action" aria-pressed="false"><?php esc_html_e('Needs Action','sabri-unified-notifications');?></button><button type="button" data-sun-smart-filter="history" aria-pressed="false"><?php esc_html_e('History','sabri-unified-notifications');?></button></nav>
<div class="sun-list" role="list" data-sun-list>
<?php if(empty($items)):?><div class="sun-empty" role="status">🔔 <strong><?php esc_html_e('No matching notifications','sabri-unified-notifications');?></strong><span><?php esc_html_e('Important updates will appear here.','sabri-unified-notifications');?></span></div><?php endif;?>
<?php foreach($items as $item):$status=(string)($item['status']??'unread');$state_version=(int)($item['state_version']??0);?>
<article class="sun-card is-<?php echo esc_attr($status);?>" role="listitem" data-sun-id="<?php echo esc_attr($item['public_id']);?>" data-sun-status="<?php echo esc_attr($status);?>" data-sun-version="<?php echo esc_attr($item['notification_version']??$item['version']??0);?>" data-sun-state-version="<?php echo esc_attr($state_version);?>" data-sun-live-revision="<?php echo esc_attr($item['live_revision']??1);?>">
<div class="sun-card__icon" aria-hidden="true"><?php echo esc_html('security'===($item['category']??'')?'🛡️':('clinic'===($item['category']??'')?'🩺':('learning'===($item['category']??'')?'📚':('messages'===($item['category']??'')?'💬':'🔔'))));?></div>
<div class="sun-card__body"><div class="sun-card__meta"><?php if(!empty($item['source_label'])):?><span class="sun-source-badge"><?php echo !empty($item['source_verified'])?'✓ ':'';echo esc_html($item['source_label']);?></span><?php endif;?><span class="sun-attention-score" title="<?php echo esc_attr($item['attention_reason']??'');?>"><?php echo esc_html((string)($item['attention_score']??50));?>/100</span><?php if(!empty($item['pinned'])):?><span>📌</span><?php endif;?></div><a href="<?php echo esc_url($item['open_url']);?>" class="sun-card__link"><strong data-sun-card-title><?php echo esc_html($item['title']);?></strong><span data-sun-card-summary><?php echo esc_html($item['summary']);?></span></a><time datetime="<?php echo esc_attr(mysql2date(DATE_W3C,$item['created_at'],false));?>"><?php echo esc_html(human_time_diff(strtotime($item['created_at'].' UTC'),time()));?> <?php esc_html_e('ago','sabri-unified-notifications');?></time></div>
<div class="sun-card__menu"><button type="button" data-sun-attention-action="<?php echo !empty($item['pinned'])?'unpin':'pin';?>"><?php echo !empty($item['pinned'])?esc_html__('Unpin','sabri-unified-notifications'):esc_html__('Pin','sabri-unified-notifications');?></button><button type="button" data-sun-attention-action="snooze" data-sun-snooze="3600"><?php esc_html_e('Snooze 1h','sabri-unified-notifications');?></button><button type="button" data-sun-attention-action="<?php echo 'needs_action'===($item['action_state']??'')?'done':'needs_action';?>"><?php echo 'needs_action'===($item['action_state']??'')?esc_html__('Done','sabri-unified-notifications'):esc_html__('Needs action','sabri-unified-notifications');?></button><button type="button" data-sun-why><?php esc_html_e('Why?','sabri-unified-notifications');?></button><button type="button" data-sun-action="<?php echo 'unread'===$status?'read':'unread';?>"><?php echo 'unread'===$status?esc_html__('Mark read','sabri-unified-notifications'):esc_html__('Mark unread','sabri-unified-notifications');?></button><button type="button" data-sun-action="<?php echo 'archived'===$status?'unarchive':'archive';?>"><?php echo 'archived'===$status?esc_html__('Unarchive','sabri-unified-notifications'):esc_html__('Archive','sabri-unified-notifications');?></button></div>
</article><?php endforeach;?>
</div><div class="sun-live-region" aria-live="polite" aria-atomic="true" data-sun-status></div></section>
