<?php
/** @var array<int,array<string,mixed>> $items */
/** @var array<int,array<string,mixed>> $subscription_items */
/** @var array<int,string> $scope_types */
if ( ! defined( 'ABSPATH' ) ) { exit; }
$grouped=array();foreach($items as $item){$grouped[$item['category']][]=$item;}
?>
<section class="sun-settings" aria-labelledby="sun-settings-title" data-sun-settings>
<header><h1 id="sun-settings-title"><?php esc_html_e('Notification settings','sabri-unified-notifications');?></h1><p><?php esc_html_e('Choose channels, quiet hours and digest frequency. Essential security alerts remain available in-app.','sabri-unified-notifications');?></p></header>
<?php foreach($grouped as $category=>$rows): ?><fieldset class="sun-settings__group"><legend><?php echo esc_html(ucwords(str_replace('_',' ',$category)));?></legend><?php foreach($rows as $row): ?><form class="sun-pref" data-sun-preference><input type="hidden" name="category" value="<?php echo esc_attr($row['category']);?>"><input type="hidden" name="channel" value="<?php echo esc_attr($row['channel']);?>"><input type="hidden" name="version" value="<?php echo esc_attr($row['version']);?>"><label><input type="checkbox" name="enabled" value="1" <?php checked($row['enabled']);?> <?php disabled(!empty($row['essential'])&&'in_app'===$row['channel']);?>> <strong><?php echo esc_html(strtoupper($row['channel']));?></strong></label><label><?php esc_html_e('Digest','sabri-unified-notifications');?><select name="digest_frequency" <?php disabled(!empty($row['essential']));?>><option value="immediate" <?php selected($row['digest_frequency'],'immediate');?>><?php esc_html_e('Immediate','sabri-unified-notifications');?></option><option value="daily" <?php selected($row['digest_frequency'],'daily');?>><?php esc_html_e('Daily','sabri-unified-notifications');?></option><option value="weekly" <?php selected($row['digest_frequency'],'weekly');?>><?php esc_html_e('Weekly','sabri-unified-notifications');?></option></select></label><label><input type="checkbox" name="quiet_enabled" value="1" <?php checked($row['quiet_enabled']);?> <?php disabled(!empty($row['essential']));?>> <?php esc_html_e('Quiet hours','sabri-unified-notifications');?></label><input type="time" name="quiet_start" value="<?php echo esc_attr(substr($row['quiet_start'],0,5));?>"><input type="time" name="quiet_end" value="<?php echo esc_attr(substr($row['quiet_end'],0,5));?>"><input type="text" name="timezone" value="<?php echo esc_attr($row['timezone']);?>" aria-label="<?php esc_attr_e('Timezone','sabri-unified-notifications');?>"><button class="sun-button" type="submit"><?php esc_html_e('Save','sabri-unified-notifications');?></button></form><?php endforeach;?></fieldset><?php endforeach;?>
<section class="sun-settings__group" aria-labelledby="sun-subscriptions-title"><h2 id="sun-subscriptions-title"><?php esc_html_e('Subscriptions','sabri-unified-notifications');?></h2><p><?php esc_html_e('Subscriptions created from doctor, topic, community, course, event and channel pages appear here. You can pause them or change their frequency without changing the underlying follow, membership or course record.','sabri-unified-notifications');?></p><?php if(empty($subscription_items)):?><p class="sun-muted"><?php esc_html_e('No scoped notification subscriptions yet. Use a Subscribe or notification control on an eligible page.','sabri-unified-notifications');?></p><?php endif;?><?php foreach($subscription_items as $sub):?><form class="sun-pref sun-subscription" data-sun-subscription><input type="hidden" name="scope_type" value="<?php echo esc_attr($sub['scope_type']);?>"><input type="hidden" name="scope_id" value="<?php echo esc_attr($sub['scope_id']);?>"><input type="hidden" name="event_pattern" value="<?php echo esc_attr($sub['event_pattern']);?>"><input type="hidden" name="version" value="<?php echo esc_attr($sub['version']);?>"><label><input type="checkbox" name="enabled" value="1" <?php checked($sub['enabled']);?>> <strong><?php echo esc_html(ucwords(str_replace('_',' ',$sub['scope_type'])));?></strong></label><span class="sun-subscription__scope"><?php echo esc_html($sub['scope_id']);?></span><span class="sun-subscription__event"><?php echo esc_html($sub['event_pattern']);?></span><label><?php esc_html_e('Frequency','sabri-unified-notifications');?><select name="frequency"><option value="immediate" <?php selected($sub['frequency'],'immediate');?>><?php esc_html_e('Immediate','sabri-unified-notifications');?></option><option value="daily" <?php selected($sub['frequency'],'daily');?>><?php esc_html_e('Daily','sabri-unified-notifications');?></option><option value="weekly" <?php selected($sub['frequency'],'weekly');?>><?php esc_html_e('Weekly','sabri-unified-notifications');?></option></select></label><button class="sun-button" type="submit"><?php esc_html_e('Save','sabri-unified-notifications');?></button></form><?php endforeach;?></section>
<section class="sun-push-optin" aria-labelledby="sun-push-title"><h2 id="sun-push-title"><?php esc_html_e('Browser notifications','sabri-unified-notifications');?></h2><p><?php esc_html_e('Permission is requested only after you press the button. Sensitive content is never placed on the lock screen.','sabri-unified-notifications');?></p><button type="button" class="sun-button" data-sun-enable-push><?php esc_html_e('Enable browser notifications','sabri-unified-notifications');?></button></section>
<div class="sun-live-region" aria-live="polite" data-sun-status></div></section>
