<?php
require __DIR__.'/bootstrap.php';
$tests=0;$failures=array();function adv_check($condition,$label){global$tests,$failures;++$tests;if(!$condition){$failures[]=$label;}}
$auth=new SUN_Auth();$attention=new SUN_Attention_Service($auth);$automation=new SUN_Automation_Service($attention);$routing=new SUN_Routing_Service();$experiments=new SUN_Experiments_Service();$trace=new SUN_Trace_Service();$intelligence=new SUN_Intelligence_Service($attention);
adv_check(in_array('study',$attention->focus_modes(),true)&&in_array('essential',$attention->focus_modes(),true),'focus modes');
adv_check(count($attention->focus_modes())===8,'focus mode inventory');
adv_check(in_array('saved_search',$automation->trigger_types(),true)&&in_array('correction',$automation->trigger_types(),true),'automation triggers');
adv_check(in_array('calendar_handoff',$automation->action_types(),true)&&in_array('owner_action',$automation->action_types(),true),'native owner automation actions');
adv_check($routing->channels()===array('email','push','sms','whatsapp','rcs'),'advanced external channels');
adv_check($experiments->types()===array('simulator','shadow','canary'),'experiment modes');
$synthetic=$trace->synthetic_test(array('in_app','email','whatsapp'));adv_check('non-delivery-dry-run'===$synthetic['mode'],'synthetic diagnostics are dry run');adv_check(3===count($synthetic['checks']),'synthetic channel inventory');
$contract=array('version'=>'3.0.0','domain_truth_owner_preserved'=>true);adv_check(true===$contract['domain_truth_owner_preserved'],'domain truth boundary');
$src=file_get_contents(dirname(__DIR__).'/19-unified-notifications/includes/class-sun-intelligence-service.php');adv_check(false!==strpos($src,'array_intersect( $source_ids'),'AI citation allowlist binding');adv_check(false!==strpos($src,'deterministic-fallback'),'AI deterministic fallback');adv_check(false!==strpos($src,'invalid_citations')&&false!==strpos($src,"'citation_boundary'"),'AI hallucinated citation rejection');
$att=file_get_contents(dirname(__DIR__).'/19-unified-notifications/includes/class-sun-attention-service.php');adv_check(false!==strpos($att,"'essential_only'")&&false!==strpos($att,'source_cap_reached'),'attention budgets and caps');adv_check(false!==strpos($att,'revoke_source')&&false!==strpos($att,'live_update'),'live/revocable projections');adv_check(false!==strpos($att,"'balanced'")&&false!==strpos($att,"'history_days' => 90"),'attention defaults present');adv_check(false!==strpos($att,"array_key_exists( 'essential_only', \$input )")&&false!==strpos($att,"array_key_exists( 'best_time_enabled', \$input )"),'partial attention updates preserve omitted booleans');adv_check(false!==strpos($att,'sun_device_profile_conflict')&&false!==strpos($att,"'version' => \$expected"),'device optimistic concurrency');adv_check(false!==strpos($att,"\$existing['handoff_ciphertext']")&&false!==strpos($att,"array_key_exists( 'handoff', \$input )"),'device handoff preservation');
$route=file_get_contents(dirname(__DIR__).'/19-unified-notifications/includes/class-sun-routing-service.php');adv_check(false!==strpos($route,'cost_known')&&false!==strpos($route,'sun_all_providers_failed'),'cost-aware provider failover');adv_check(false!==strpos($route,"CASE health_state WHEN 'healthy'")&&false!==strpos($route,"WHEN 'degraded' THEN 2"),'provider health affects route order');
$automation_src=file_get_contents(dirname(__DIR__).'/19-unified-notifications/includes/class-sun-automation-service.php');adv_check(false!==strpos($automation_src,'trigger_owner')&&false!==strpos($automation_src,'array( $producer, $owner )'),'saved-search owner binding');adv_check(false!==strpos($automation_src,"array_key_exists( 'enabled', \$input )"),'rule partial update preserves enabled state');adv_check(false!==strpos($automation_src,'sun_rule_category_invalid')&&false!==strpos($automation_src,'sun_rule_source_invalid'),'empty automation triggers rejected');
$privacy=file_get_contents(dirname(__DIR__).'/19-unified-notifications/includes/class-sun-privacy.php');foreach(array('attention_profiles','notification_rules','device_profiles','watch_history') as $needle){adv_check(false!==strpos($privacy,$needle),'privacy lifecycle '.$needle);}adv_check(substr_count($privacy,'LIMIT %d OFFSET %d')>=4,'advanced privacy export pagination');adv_check(false!==strpos($privacy,'count($states)<$limit')&&false!==strpos($privacy,'count($watch)<$limit'),'privacy export completion accounts for advanced pages');
$advanced_rest=file_get_contents(dirname(__DIR__).'/19-unified-notifications/includes/class-sun-advanced-rest.php');adv_check(false!==strpos($advanced_rest,"'permission_callback'=>array(\$this,'can_view_routing_cost')")&&false!==strpos($advanced_rest,'can_view_routing_cost'),'routing cost evidence is privileged');
$doc=file_get_contents(dirname(__DIR__).'/19-unified-notifications/docs/ADVANCED-ATTENTION-OS-3.0.0.md');for($i=1;$i<=48;$i++){adv_check(false!==strpos($doc,sprintf('F19-AF-%03d',$i)),'advanced requirement '.sprintf('%03d',$i));}
if($failures){fwrite(STDERR,"FAIL (".count($failures)."/$tests):\n - ".implode("\n - ",$failures)."\n");exit(1);}echo "PASS: $tests File 19 3.0 advanced deterministic regression assertions\n";
