#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)";PLUGIN="$ROOT/19-unified-notifications";fail(){ echo "FAIL: $*" >&2; exit 1; }
find "$PLUGIN" -name '*.php' -print0 | xargs -0 -n1 php -l >/dev/null
node --check "$PLUGIN/assets/js/notifications.js" >/dev/null;node --check "$PLUGIN/assets/js/push-service-worker.js" >/dev/null
[[ -f "$PLUGIN/19-unified-notifications.php" ]]||fail "bootstrap missing";grep -q "Version: 3.0.1" "$PLUGIN/19-unified-notifications.php"||fail "version mismatch";grep -q "Requires at least: 7.0" "$PLUGIN/19-unified-notifications.php"||fail "WordPress baseline mismatch";grep -q "Requires PHP: 8.3" "$PLUGIN/19-unified-notifications.php"||fail "PHP baseline mismatch"
for class in database crypto audit four-plan-compliance operational-gate provider-circuit auth producer-registry event-validator template-engine preferences subscriptions policy-engine deep-link delivery-service notification-service bulk-service reconciliation health wellbeing rest-controller renderer router admin privacy activator plugin advanced-activator trace-service attention-service intelligence-service automation-service routing-service experiments-service advanced-rest routed-adapter;do [[ -f "$PLUGIN/includes/class-sun-$class.php" ]]||fail "missing class $class";done
for table in events notifications preferences subscriptions deliveries templates policies devices dead_letters audit bulk_jobs attention_profiles notification_states notification_rules device_profiles provider_routes experiments trace_spans watch_history;do grep -q "'$table'" "$PLUGIN/includes/class-sun-database.php" "$PLUGIN/includes/class-sun-advanced-activator.php" >/dev/null||fail "schema domain $table missing";done
for cv in CV-097 CV-098 CV-099 CV-100 CV-101 CV-102 CV-103 CV-104 CV-105 CV-106;do grep -q "$cv" "$PLUGIN/includes/class-sun-four-plan-compliance.php"||fail "Top-20 capability $cv missing";done
for i in $(seq -w 1 48);do id="F19-AF-0${i}"; [[ ${#i} -eq 2 ]] && id="F19-AF-0${i}"; grep -q "$id" "$PLUGIN/docs/ADVANCED-ATTENTION-OS-3.0.0.md"||fail "advanced requirement $id missing";done
grep -q "sabri_membership_claims_v2" "$PLUGIN/includes/class-sun-auth.php"||fail "File 00 canonical claims missing";! grep -q "sun_identity_assertions" "$PLUGIN/includes/class-sun-auth.php"||fail "local identity privilege filter reintroduced"
grep -q "sun_event_owner_mismatch" "$PLUGIN/includes/class-sun-event-validator.php"||fail "producer owner binding missing";grep -q "sun_event_data_complexity_exceeded" "$PLUGIN/includes/class-sun-event-validator.php"||fail "payload complexity bound missing";! grep -q "sun_validated_event" "$PLUGIN/includes/class-sun-event-validator.php"||fail "post-validation mutation hook reintroduced"
grep -q "authorize_click" "$PLUGIN/includes/class-sun-deep-link.php"||fail "click-time authorization missing";grep -q "sun_notification_decrypt_failed" "$PLUGIN/includes/class-sun-delivery-service.php"||fail "decrypt fail-closed missing";grep -q "notification_expired" "$PLUGIN/includes/class-sun-delivery-service.php"||fail "expiry terminal path missing"
grep -q "more-notifications-is-not-a-kpi" "$PLUGIN/includes/class-sun-wellbeing.php" "$PLUGIN/includes/class-sun-attention-service.php" >/dev/null||fail "wellbeing guardrail missing"
grep -q "invalid_citations" "$PLUGIN/includes/class-sun-intelligence-service.php"||fail "AI invalid-citation rejection missing";grep -q "citation_boundary" "$PLUGIN/includes/class-sun-intelligence-service.php"||fail "AI citation boundary missing";grep -q "deterministic-fallback" "$PLUGIN/includes/class-sun-intelligence-service.php"||fail "AI deterministic fallback missing"
grep -q "array_key_exists( 'essential_only'" "$PLUGIN/includes/class-sun-attention-service.php"||fail "partial profile preservation missing";grep -q "sun_device_profile_conflict" "$PLUGIN/includes/class-sun-attention-service.php"||fail "device concurrency guard missing";grep -q "handoff_ciphertext" "$PLUGIN/includes/class-sun-attention-service.php"||fail "device handoff preservation missing";grep -q "source_cap_reached" "$PLUGIN/includes/class-sun-attention-service.php"||fail "adaptive frequency cap missing";grep -q "live_update" "$PLUGIN/includes/class-sun-attention-service.php"||fail "live update missing";grep -q "revoke_source" "$PLUGIN/includes/class-sun-attention-service.php"||fail "revocation missing"
grep -q "trigger_owner" "$PLUGIN/includes/class-sun-automation-service.php"||fail "saved-search owner binding missing";grep -q "sun_rule_category_invalid" "$PLUGIN/includes/class-sun-automation-service.php"||fail "empty category trigger rejection missing";grep -q "array_key_exists( 'enabled'" "$PLUGIN/includes/class-sun-automation-service.php"||fail "rule partial update preservation missing"
grep -q "whatsapp" "$PLUGIN/includes/class-sun-preferences.php"||fail "WhatsApp opt-in channel missing";grep -q "rcs" "$PLUGIN/includes/class-sun-preferences.php"||fail "RCS opt-in channel missing";grep -q "fcm" "$PLUGIN/includes/class-sun-advanced-activator.php"||fail "FCM route missing";grep -q "apns" "$PLUGIN/includes/class-sun-advanced-activator.php"||fail "APNs route missing"
grep -q "CASE health_state WHEN 'healthy'" "$PLUGIN/includes/class-sun-routing-service.php"||fail "provider health ordering missing";grep -q "sun_all_providers_failed" "$PLUGIN/includes/class-sun-routing-service.php"||fail "provider failover missing";grep -q "cost_known" "$PLUGIN/includes/class-sun-routing-service.php"||fail "cost-aware routing missing";grep -q "can_view_routing_cost" "$PLUGIN/includes/class-sun-advanced-rest.php"||fail "routing-cost privilege gate missing";grep -q "simulator.*shadow.*canary" "$PLUGIN/includes/class-sun-experiments-service.php"||fail "experiment modes missing"
grep -q "non-delivery-dry-run" "$PLUGIN/includes/class-sun-trace-service.php"||fail "synthetic truth boundary missing";grep -q "trace_spans" "$PLUGIN/includes/class-sun-trace-service.php"||fail "trace explorer missing"
for domain in attention_profiles notification_rules device_profiles watch_history;do grep -q "$domain" "$PLUGIN/includes/class-sun-privacy.php"||fail "privacy lifecycle missing $domain";done
grep -q 'count($states)<$limit' "$PLUGIN/includes/class-sun-privacy.php"||fail "paginated attention-state privacy export missing";grep -q 'count($watch)<$limit' "$PLUGIN/includes/class-sun-privacy.php"||fail "paginated watch-history privacy export missing"
for domain in attention_profiles notification_states notification_rules device_profiles provider_routes experiments trace_spans watch_history;do grep -q "$domain" "$PLUGIN/uninstall.php"||fail "uninstall missing $domain";done
grep -q "\.sun-live-region\[data-sun-status\]" "$PLUGIN/assets/js/notifications.js"||fail "live-region selector regression";grep -q 'data-sun-action=.*read' "$PLUGIN/assets/js/notifications.js"||fail "dynamic mark-read action missing";grep -q 'data-sun-action=.*archive' "$PLUGIN/assets/js/notifications.js"||fail "dynamic archive action missing";grep -q "min-height:44px" "$PLUGIN/assets/css/notifications.css"||fail "44px target law missing"
! grep -RInE '\beval\s*\(|\bexec\s*\(|\bshell_exec\s*\(|\bpassthru\s*\(|\bunserialize\s*\(' "$PLUGIN" --include='*.php'||fail "dangerous function found";! grep -RInE "(api[_-]?key|secret|token)[[:space:]]*=[[:space:]]*['\"][A-Za-z0-9+/=_-]{20,}" "$PLUGIN"||fail "possible embedded secret"
echo "PASS: File 19 3.0.1 intelligent attention security/privacy regression audit"
