<?php
require __DIR__.'/bootstrap.php';
$tests=0;$failures=array();
function check($condition,$label){global $tests,$failures;++$tests;if(!$condition){$failures[]=$label;}}
check(SUN_Database::canonical_json(array('b'=>2,'a'=>1))==='{"a":1,"b":2}','canonical JSON sorting');
check((bool)preg_match('/^[a-f0-9\-]{36}$/',SUN_Database::uuid()),'UUID format');
$cipher=SUN_Crypto::encrypt('private payload');check(!is_wp_error($cipher),'encryption available');check(SUN_Crypto::decrypt($cipher)==='private payload','encryption round trip');
$token=SUN_Crypto::sign_token(array('purpose'=>'unsubscribe','user_id'=>7),300);$claims=SUN_Crypto::verify_token($token,'unsubscribe');check(!is_wp_error($claims)&&7===$claims['user_id'],'signed token verification');check(is_wp_error(SUN_Crypto::verify_token($token,'other')),'token purpose binding');
check(SUN_Deep_Link::sanitize('/notifications/')==='https://sabrihomeopathy.com/notifications/','relative deep-link normalization');
check(SUN_Deep_Link::sanitize('https://evil.example/path')==='','cross-origin host rejection');
check(SUN_Deep_Link::sanitize('http://sabrihomeopathy.com/path')==='','same-host scheme downgrade rejection');
check(SUN_Deep_Link::sanitize('https://sabrihomeopathy.com:444/path')==='','same-host alternate-port rejection');
check(SUN_Deep_Link::sanitize('https://user:pass@sabrihomeopathy.com/path')==='','credentialed URL rejection');
check(SUN_Deep_Link::sanitize('javascript:alert(1)')==='','unsafe scheme rejection');
$compliance=SUN_Four_Plan_Compliance::snapshot();check(4===count($compliance['governing_plans']),'four governing plans registered');check('green'===$compliance['brand_primary'],'green central brand');check(true===$compliance['single_free_tier']&&!$compliance['donor_advantage'],'single free tier and no donor advantage');check(26===$compliance['search_owner_file']&&20===$compliance['shell_owner_file'],'canonical search and shell owners');
check(true===SUN_Operational_Gate::allows('external_delivery'),'external delivery allowed outside safe mode');
$GLOBALS['sun_test_options']['sun_notification_safe_mode']=1;check(false===SUN_Operational_Gate::allows('external_delivery'),'external delivery blocked in safe mode');check(false===SUN_Operational_Gate::allows('bulk_process'),'bulk processing blocked in safe mode');unset($GLOBALS['sun_test_options']['sun_notification_safe_mode']);
for($i=0;$i<5;$i++){SUN_Provider_Circuit::record_failure('push');}check(true===SUN_Provider_Circuit::is_open('push'),'provider circuit opens after repeated failures');SUN_Provider_Circuit::record_success('push');check(false===SUN_Provider_Circuit::is_open('push'),'provider circuit resets after success');
$auth=new SUN_Auth();check(false===$auth->is_recipient_eligible(5),'File 00 unavailable fails closed');
add_filter('sabri_membership_claims_v2',function($value,$user_id){return array('active'=>true,'verified'=>true,'email_verified'=>true,'phone_verified'=>true,'suspended'=>false,'revoked'=>false,'risk_blocked'=>false,'guardian_ok'=>true,'consent_ok'=>true,'step_up_verified'=>true,'founder'=>true,'institutional_role'=>'founder','locale'=>'ur','timezone'=>'Asia/Karachi');});
check(true===$auth->is_recipient_eligible(5),'verified active File 00 claim permits recipient');
$assertions=$auth->assertions(5);check(true===$assertions['owner_available']&&'Asia/Karachi'===$assertions['timezone'],'canonical claims projected');check(true===$assertions['email_verified']&&true===$assertions['phone_verified'],'verified channel claims projected');check(true===$assertions['step_up_verified']&&true===$assertions['founder'],'governance claims projected');
$registry=new SUN_Producer_Registry();check(true===$registry->authorize_type('sabri-system','System.HealthChanged'),'default producer authorization');check(is_wp_error($registry->authorize_type('sabri-system','Marketplace.DealChanged')),'producer type denial');
SUN_Producer_Registry::register_runtime('file17',array('owner'=>'File 17','event_types'=>array('Communication.*'),'schema_versions'=>array('1.0')));check(true===$registry->authorize_type('file17','Communication.MessageReceived'),'runtime producer');
$validator=new SUN_Event_Validator($registry);$event=array('producer'=>'file17','owner'=>'File 17','event_id'=>'msg:1','event_type'=>'Communication.MessageReceived','schema_version'=>'1.0','occurred_at'=>gmdate(DATE_ATOM),'recipients'=>array(array('user_id'=>5),array('user_id'=>5)),'data'=>array('summary'=>'Private message'));$valid=$validator->validate($event);check(!is_wp_error($valid)&&1===count($valid['recipients']),'event validation and recipient dedupe');
$bad_owner=$event;$bad_owner['owner']='File 18';check(is_wp_error($validator->validate($bad_owner))&&'sun_event_owner_mismatch'===$validator->validate($bad_owner)->get_error_code(),'producer owner binding');
$bad_schema=$event;$bad_schema['schema_version']='2.0';check(is_wp_error($validator->validate($bad_schema))&&'sun_schema_version_unsupported'===$validator->validate($bad_schema)->get_error_code(),'producer schema allowlist');
$event['recipients']=array(array('role'=>'subscriber'));check(is_wp_error($validator->validate($event)),'broad role recipient rejection');
$event['recipients']=array(5);$event['event_type']='bad type';check(is_wp_error($validator->validate($event)),'invalid event type rejection');
$engine=new SUN_Template_Engine();check(true===$engine->validate_template('{{action_name}}','{{summary}}',array('action_name','summary')),'safe template validation');check(is_wp_error($engine->validate_template('<script>alert(1)</script>','x',array())),'script template rejection');check(is_wp_error($engine->validate_template('{{secret}}','x',array('summary'))),'unknown variable rejection');
$render=$engine->render(array('title_template'=>'{{action_name}}','body_template'=>'{{summary}}','allowed_variables'=>'["action_name","summary"]'),array('action_name'=>'Ready','summary'=>'Done'),'email','sensitive');check($render['title']==='You have a new private update','sensitive external redaction');
if($failures){fwrite(STDERR,"FAIL (".count($failures)."/$tests):\n - ".implode("\n - ",$failures)."\n");exit(1);}echo "PASS: $tests deterministic unit assertions\n";
