<?php
require __DIR__.'/bootstrap.php';
$tests=0;$failures=array();
function check($condition,$label){global $tests,$failures;++$tests;if(!$condition){$failures[]=$label;}}
check(SUN_Database::canonical_json(array('b'=>2,'a'=>1))==='{"a":1,"b":2}','canonical JSON sorting');
check((bool)preg_match('/^[a-f0-9\-]{36}$/',SUN_Database::uuid()),'UUID format');
$cipher=SUN_Crypto::encrypt('private payload');check(!is_wp_error($cipher),'encryption available');check(SUN_Crypto::decrypt($cipher)==='private payload','encryption round trip');
$token=SUN_Crypto::sign_token(array('purpose'=>'unsubscribe','user_id'=>7),300);$claims=SUN_Crypto::verify_token($token,'unsubscribe');check(!is_wp_error($claims)&&7===$claims['user_id'],'signed token verification');check(is_wp_error(SUN_Crypto::verify_token($token,'other')),'token purpose binding');
check(SUN_Deep_Link::sanitize('/notifications/')==='https://sabrihomeopathy.com/notifications/','relative deep-link normalization');
check(SUN_Deep_Link::sanitize('https://evil.example/path')==='','cross-origin deep-link rejection');
check(SUN_Deep_Link::sanitize('javascript:alert(1)')==='','unsafe scheme rejection');
$compliance=SUN_Four_Plan_Compliance::snapshot();
check(4===count($compliance['governing_plans']),'four governing plans registered');
check('green'===$compliance['brand_primary'],'green central brand');
check(true===$compliance['single_free_tier']&&!$compliance['donor_advantage'],'single free tier and no donor advantage');
check(26===$compliance['search_owner_file']&&20===$compliance['shell_owner_file'],'canonical search and shell owners');
check('unified-notifications-19'===$compliance['package_top_folder'],'canonical package top folder');
check('7.0.1'===$compliance['project_baseline']['wordpress']&&'8.3'===$compliance['project_baseline']['php'],'current project runtime baseline');
check(10===count($compliance['top20_capabilities']),'Top-20 notification capability family CV-097 through CV-106');
check(isset($compliance['event_catalog']['Clinic.AppointmentBooked'],$compliance['event_catalog']['Publishing.RetractionPublished'],$compliance['event_catalog']['Security.NewDeviceDetected'],$compliance['event_catalog']['Social.CreatorBulletinPublished']),'Top-20 semantic event catalog');
$auth=new SUN_Auth();check(false===$auth->is_recipient_eligible(5),'File 00 unavailable fails closed');
add_filter('sabri_membership_claims_v2',function($value,$user_id){return array('active'=>true,'verified'=>true,'email_verified'=>true,'phone_verified'=>true,'suspended'=>false,'revoked'=>false,'risk_blocked'=>false,'guardian_ok'=>true,'consent_ok'=>true,'founder'=>true,'institutional_role'=>'founder','locale'=>'ur','timezone'=>'Asia/Karachi');});
check(true===$auth->is_recipient_eligible(5),'verified active File 00 claim permits recipient');
$assertions=$auth->assertions(5);check(true===$assertions['owner_available']&&'Asia/Karachi'===$assertions['timezone'],'canonical claims projected');
check(true===$assertions['email_verified']&&true===$assertions['phone_verified'],'canonical channel verification claims preserved');
check(true===$assertions['founder']&&'founder'===$assertions['institutional_role'],'canonical Founder claims preserved');
check(true===$auth->is_founder(5),'canonical File 00 Founder claim authorizes Founder identity');
$registry=new SUN_Producer_Registry();check(true===$registry->authorize_type('sabri-system','System.HealthChanged'),'default producer authorization');check(is_wp_error($registry->authorize_type('sabri-system','Marketplace.DealChanged')),'producer type denial');
SUN_Producer_Registry::register_runtime('file17',array('owner'=>'File 17','event_types'=>array('Communication.*')));check(true===$registry->authorize_type('file17','Communication.MessageReceived'),'runtime producer');
$validator=new SUN_Event_Validator($registry);
$event=array('producer'=>'file17','owner'=>'File 17','event_id'=>'msg:1','event_type'=>'Communication.MessageReceived','schema_version'=>'1.0','occurred_at'=>gmdate(DATE_ATOM),'recipients'=>array(array('user_id'=>5),array('user_id'=>5)),'subscription_scope'=>array('type'=>'community','id'=>'community-9','required'=>true),'data'=>array('summary'=>'Private message'));
$valid=$validator->validate($event);check(!is_wp_error($valid)&&1===count($valid['recipients']),'event validation and recipient dedupe');
check('community'===$valid['subscription_scope']['type']&&true===$valid['subscription_scope']['required'],'granular subscription scope normalization');
$wrong_owner=$event;$wrong_owner['owner']='File 08';$wrong_owner_result=$validator->validate($wrong_owner);check(is_wp_error($wrong_owner_result)&&'sun_event_owner_mismatch'===$wrong_owner_result->get_error_code(),'producer cannot forge domain owner');
$bad_scope=$event;$bad_scope['subscription_scope']=array('type'=>'private_message_body','id'=>'x','required'=>true);check(is_wp_error($validator->validate($bad_scope)),'invalid subscription scope rejected');
$event['recipients']=array(array('role'=>'subscriber'));check(is_wp_error($validator->validate($event)),'broad role recipient rejection');
$event['recipients']=array(5);$event['event_type']='bad type';check(is_wp_error($validator->validate($event)),'invalid event type rejection');
SUN_Producer_Registry::register_runtime('file21',array('owner'=>'File 21','event_types'=>array('Social.*','Publishing.*')));
$bulletin=array('producer'=>'file21','owner'=>'File 21','event_id'=>'bulletin:1','event_type'=>'Social.CreatorBulletinPublished','schema_version'=>'1.0','occurred_at'=>gmdate(DATE_ATOM),'recipients'=>array(5),'data'=>array('summary'=>'Bulletin'));
$bulletin_without_scope=$validator->validate($bulletin);check(is_wp_error($bulletin_without_scope)&&'sun_subscription_scope_required'===$bulletin_without_scope->get_error_code(),'creator bulletin requires explicit opt-in scope');
$bulletin['subscription_scope']=array('type'=>'person','id'=>'doctor-55','required'=>true);check(!is_wp_error($validator->validate($bulletin)),'creator bulletin accepts explicit required subscription scope');
$subscriptions=new SUN_Subscriptions();check(array('person','topic','community','course','event','doctor','channel')===$subscriptions->scope_types(),'Top-20 subscription scope types');check(array('immediate','daily','weekly')===$subscriptions->frequencies(),'Top-20 subscription frequencies');
$engine=new SUN_Template_Engine();check(true===$engine->validate_template('{{action_name}}','{{summary}}',array('action_name','summary')),'safe template validation');check(is_wp_error($engine->validate_template('<script>alert(1)</script>','x',array())),'script template rejection');check(is_wp_error($engine->validate_template('{{secret}}','x',array('summary'))),'unknown variable rejection');
$render=$engine->render(array('title_template'=>'{{action_name}}','body_template'=>'{{summary}}','allowed_variables'=>'["action_name","summary"]'),array('action_name'=>'Ready','summary'=>'Done'),'email','sensitive');check($render['title']==='You have a new private update','sensitive external redaction');
if($failures){fwrite(STDERR,"FAIL (".count($failures)."/$tests):\n - ".implode("\n - ",$failures)."\n");exit(1);}echo "PASS: $tests deterministic unit assertions\n";
