<?php
/** Cost-aware, provider-neutral routing and failover for external notification channels. */
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class SUN_Routing_Service {
    /** @return string[] */ public function channels() { return array( 'email', 'push', 'sms', 'whatsapp', 'rcs' ); }
    /** @param string $channel Channel. @return array<int,array<string,mixed>> */
    public function candidates( $channel ) { global $wpdb; $channel = sanitize_key( $channel ); if ( ! in_array( $channel, $this->channels(), true ) ) { return array(); } $rows = $wpdb->get_results( $wpdb->prepare( "SELECT public_id,channel,provider_key,priority,enabled,cost_micros,cost_known,regions_json,max_per_hour,config_key,health_state FROM " . SUN_Database::table( 'provider_routes' ) . " WHERE channel=%s AND enabled=1 ORDER BY CASE health_state WHEN 'healthy' THEN 0 WHEN 'unknown' THEN 1 WHEN 'degraded' THEN 2 ELSE 3 END ASC,priority DESC,cost_known DESC,cost_micros ASC,id ASC LIMIT 20", $channel ), ARRAY_A ); foreach ( (array) $rows as &$row ) { $row['enabled'] = (bool) $row['enabled']; $row['cost_known'] = (bool) $row['cost_known']; $row['regions'] = json_decode( (string) $row['regions_json'], true ) ?: array(); unset( $row['regions_json'] ); } unset( $row ); return (array) $rows; }

    /** @param string $channel Channel. @param SUN_Delivery_Adapter|null $base Base adapter. @param array<string,mixed> $delivery Delivery. @param array<string,mixed> $notification Notification. @return array<string,mixed>|WP_Error */
    public function send( $channel, $base, array $delivery, array $notification ) {
        $channel = sanitize_key( $channel ); $base_key = $this->base_provider_key( $channel ); $errors = array(); $candidates = $this->candidates( $channel );
        if ( empty( $candidates ) && $base instanceof SUN_Delivery_Adapter ) { return $base->send( $delivery, $notification ); }
        foreach ( $candidates as $candidate ) { $provider = sanitize_key( (string) $candidate['provider_key'] ); if ( ! $this->within_provider_cap( $candidate ) ) { $errors[] = $provider . ':rate_cap'; continue; }
            if ( $base instanceof SUN_Delivery_Adapter && $provider === $base_key ) { $result = $base->send( $delivery, $notification ); }
            else { $result = apply_filters( 'sun_send_routed_notification', null, $provider, $channel, $delivery, $notification, $candidate ); if ( null === $result ) { $result = new WP_Error( 'sun_routed_provider_unconfigured', __( 'The routed notification provider is not configured.', 'sabri-unified-notifications' ) ); } }
            if ( is_wp_error( $result ) ) { $errors[] = $provider . ':' . sanitize_key( $result->get_error_code() ); $this->record_health( $channel, $provider, false ); continue; }
            if ( is_array( $result ) && in_array( (string) ( $result['status'] ?? '' ), array( 'accepted', 'delivered', 'suppressed' ), true ) ) { $result['provider'] = sanitize_key( (string) ( $result['provider'] ?? $provider ) ); $result['route_provider'] = $provider; $result['estimated_cost_micros'] = ! empty( $candidate['cost_known'] ) ? (int) $candidate['cost_micros'] : null; $this->record_health( $channel, $provider, true ); SUN_Audit::record( 'delivery_route_selected', 'delivery', (string) ( $delivery['public_id'] ?? '' ), array( 'channel' => $channel, 'provider' => $provider, 'cost_known' => ! empty( $candidate['cost_known'] ), 'purpose' => 'delivery_routing' ), 0 ); return $result; }
            $errors[] = $provider . ':invalid_result'; $this->record_health( $channel, $provider, false );
        }
        if ( $base instanceof SUN_Delivery_Adapter && ! in_array( $base_key, array_map( static function( $c ) { return sanitize_key( (string) $c['provider_key'] ); }, $candidates ), true ) ) { $fallback = $base->send( $delivery, $notification ); if ( ! is_wp_error( $fallback ) ) { return $fallback; } $errors[] = $base_key . ':' . sanitize_key( $fallback->get_error_code() ); }
        return new WP_Error( 'sun_all_providers_failed', __( 'No configured notification provider accepted this delivery.', 'sabri-unified-notifications' ), array( 'attempts' => array_slice( $errors, 0, 20 ) ) );
    }

    /** @param int $user_id User ID. @param string $channel Channel. @return array<string,mixed> */
    public function cost_snapshot( $user_id, $channel = '' ) { global $wpdb; $user_id = absint( $user_id ); $where = 'd.recipient_id=%d'; $params = array( $user_id ); if ( $channel ) { $where .= ' AND d.channel=%s'; $params[] = sanitize_key( $channel ); } $rows = $wpdb->get_results( $wpdb->prepare( 'SELECT d.channel,d.provider,COUNT(*) AS sends,r.cost_micros,r.cost_known FROM ' . SUN_Database::table( 'deliveries' ) . ' d LEFT JOIN ' . SUN_Database::table( 'provider_routes' ) . ' r ON r.channel=d.channel AND r.provider_key=d.provider WHERE ' . $where . ' AND d.created_at>=%s GROUP BY d.channel,d.provider,r.cost_micros,r.cost_known LIMIT 100', array_merge( $params, array( gmdate( 'Y-m-d H:i:s', time() - 30 * DAY_IN_SECONDS ) ) ) ), ARRAY_A ); $known = 0; foreach ( (array) $rows as &$row ) { $row['sends'] = (int) $row['sends']; $row['cost_known'] = (bool) $row['cost_known']; $row['estimated_cost_micros'] = $row['cost_known'] ? $row['sends'] * (int) $row['cost_micros'] : null; if ( null !== $row['estimated_cost_micros'] ) { $known += $row['estimated_cost_micros']; } } unset( $row ); return array( 'period_days' => 30, 'known_estimated_cost_micros' => $known, 'routes' => (array) $rows, 'truth_note' => 'Unknown provider prices remain unknown; they are never fabricated.' ); }
    /** @param string $channel Channel. @param string $provider Provider. @param bool $success Success. @return void */ public function record_health( $channel, $provider, $success ) { global $wpdb; $wpdb->update( SUN_Database::table( 'provider_routes' ), array( 'health_state' => $success ? 'healthy' : 'degraded', 'updated_at' => SUN_Database::now() ), array( 'channel' => sanitize_key( $channel ), 'provider_key' => sanitize_key( $provider ) ) ); }
    /** @param array<string,mixed> $candidate Candidate. @return bool */ private function within_provider_cap( array $candidate ) { global $wpdb; $cap = absint( $candidate['max_per_hour'] ?? 0 ); if ( $cap < 1 ) { return true; } $count = (int) $wpdb->get_var( $wpdb->prepare( 'SELECT COUNT(*) FROM ' . SUN_Database::table( 'deliveries' ) . ' WHERE channel=%s AND provider=%s AND created_at>=%s', sanitize_key( (string) $candidate['channel'] ), sanitize_key( (string) $candidate['provider_key'] ), gmdate( 'Y-m-d H:i:s', time() - HOUR_IN_SECONDS ) ) ); return $count < $cap; }
    /** @param string $channel Channel. @return string */ private function base_provider_key( $channel ) { $map = array( 'email' => 'wordpress-mail', 'push' => 'webpush', 'sms' => 'default-sms' ); return $map[ $channel ] ?? ''; }
}
