<?php
/** Notification, delivery, counter, device and schema reconciliation. */
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class SUN_Reconciliation {
	/** @var SUN_Delivery_Service */ private $delivery; /** @var SUN_Notification_Service */ private $notifications; /** @var SUN_Attention_Service|null */ private $attention;
	/** @param SUN_Delivery_Service $delivery Delivery. @param SUN_Notification_Service $notifications Notifications. @param SUN_Attention_Service|null $attention Attention repair service. */ public function __construct(SUN_Delivery_Service $delivery,SUN_Notification_Service $notifications,$attention=null){$this->delivery=$delivery;$this->notifications=$notifications;$this->attention=$attention instanceof SUN_Attention_Service?$attention:null;}
	/** @return array<string,int> */
	public function run(){global $wpdb;$now=SUN_Database::now();$result=array('expired_notifications'=>$this->notifications->expire_due(),'stale_devices'=>(int)$wpdb->query($wpdb->prepare("UPDATE ".SUN_Database::table('devices')." SET status='expired',updated_at=%s WHERE status IN ('pending','active','stale') AND expires_at IS NOT NULL AND expires_at<=%s",$now,$now)),'stuck_deliveries'=>(int)$wpdb->query($wpdb->prepare("UPDATE ".SUN_Database::table('deliveries')." SET status='failed',last_error_code='worker_timeout',last_error_safe='Delivery worker timed out.',next_attempt_at=%s,updated_at=%s WHERE status='sending' AND last_attempt_at<%s",$now,$now,gmdate('Y-m-d H:i:s',time()-15*MINUTE_IN_SECONDS))),'orphan_deliveries'=>0,'dead_letter_duplicates'=>0,'missing_attention_states'=>$this->attention?$this->attention->repair_missing_states(250):0,'delivery_failure_events_reconciled'=>0,'expired_idempotency'=>(int)$wpdb->query($wpdb->prepare('DELETE FROM '.SUN_Database::table('request_idempotency').' WHERE expires_at<=%s',$now)),'expired_webhook_receipts'=>(int)$wpdb->query($wpdb->prepare('DELETE FROM '.SUN_Database::table('webhook_receipts').' WHERE expires_at<=%s',$now)));$delivery_table=SUN_Database::table('deliveries');$notes_table=SUN_Database::table('notifications');$result['orphan_deliveries']=(int)$wpdb->query($wpdb->prepare("UPDATE {$delivery_table} d LEFT JOIN {$notes_table} n ON n.id=d.notification_id SET d.status='suppressed',d.last_error_code='orphan_notification',d.last_error_safe='Notification no longer exists.',d.updated_at=%s WHERE n.id IS NULL AND d.status IN ('queued','failed','sending')",$now));$result['delivery_failure_events_reconciled']=$this->reconcile_delivery_failure_events(100);SUN_Audit::record('reconciliation_completed','system','file-19',array_merge($result,array('purpose'=>'reconciliation')),0);update_option('sun_last_reconciliation',array('at'=>$now,'result'=>$result),false);return $result;}
	/** Republish durable delivery-failure facts through File 01 using the same idempotency identities. @return int */
	private function reconcile_delivery_failure_events($limit=100){
		if(!SUN_Platform_Events::backbone_available()){return 0;}
		global $wpdb;$limit=max(1,min(500,absint($limit)));$table=SUN_Database::table('deliveries');
		$rows=$wpdb->get_results($wpdb->prepare("SELECT public_id,channel,status,attempt_count,last_error_code,provider_message_id FROM {$table} WHERE status IN ('failed','dead_letter','bounced') AND attempt_count>0 ORDER BY updated_at DESC LIMIT %d",$limit),ARRAY_A);
		$count=0;
		foreach((array)$rows as $row){
			$status=sanitize_key((string)$row['status']);$attempt=(int)$row['attempt_count'];$provider_failure=!empty($row['provider_message_id'])&&in_array($status,array('failed','bounced'),true);
			$dedupe=$provider_failure?'delivery-failed:'.(string)$row['public_id'].':'.$attempt.':provider-'.$status:'delivery-failed:'.(string)$row['public_id'].':'.$attempt;
			$error_code=$provider_failure?'provider_'.$status:sanitize_key((string)($row['last_error_code']?:'delivery_failed'));
			$published=SUN_Platform_Events::publish('NotificationDeliveryFailed.v1',(string)$row['public_id'],array('delivery_public_id'=>(string)$row['public_id'],'channel'=>sanitize_key((string)$row['channel']),'attempt'=>$attempt,'terminal'=>in_array($status,array('dead_letter','bounced'),true),'error_code'=>$error_code),$dedupe);
			if(!is_wp_error($published)){++$count;}
		}
		return $count;
	}

	/** @param string $public_id Dead-letter public ID. @return true|WP_Error */
	public function retry_dead_letter($public_id){global $wpdb;$dead_table=SUN_Database::table('dead_letters');$delivery_table=SUN_Database::table('deliveries');$dead=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$dead_table} WHERE public_id=%s AND status='open' LIMIT 1",sanitize_text_field($public_id)),ARRAY_A);if(!$dead||empty($dead['delivery_id'])){return new WP_Error('sun_dead_letter_not_found',__('Dead-letter item not found.','sabri-unified-notifications'),array('status'=>404));}SUN_Database::begin();try{$delivery_updated=$wpdb->update($delivery_table,array('status'=>'queued','attempt_count'=>0,'next_attempt_at'=>SUN_Database::now(),'last_error_code'=>null,'last_error_safe'=>null,'updated_at'=>SUN_Database::now()),array('id'=>(int)$dead['delivery_id'],'status'=>'dead_letter'));if(1!==(int)$delivery_updated){throw new RuntimeException('delivery_transition_failed');}$dead_updated=$wpdb->update($dead_table,array('status'=>'resolved','resolved_by'=>get_current_user_id(),'resolved_at'=>SUN_Database::now(),'updated_at'=>SUN_Database::now()),array('id'=>(int)$dead['id'],'status'=>'open'));if(1!==(int)$dead_updated){throw new RuntimeException('dead_letter_transition_failed');}SUN_Database::commit();}catch(Throwable $e){SUN_Database::rollback();return new WP_Error('sun_dead_letter_retry_failed',__('The delivery could not be requeued.','sabri-unified-notifications'),array('status'=>409));}SUN_Audit::record('dead_letter_retried','dead_letter',$public_id,array('delivery_id'=>(int)$dead['delivery_id'],'purpose'=>'operator_recovery'));return true;}
}
