<?php
/** Plugin dependency graph and WordPress lifecycle coordinator. */
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class SUN_Plugin {
	/** @var self|null */ private static $instance=null;
	/** @var SUN_Auth */ private $auth; /** @var SUN_Producer_Registry */ private $registry; /** @var SUN_Preferences */ private $preferences; /** @var SUN_Subscriptions */ private $subscriptions; /** @var SUN_Notification_Service */ private $notifications; /** @var SUN_Renderer */ private $renderer; /** @var SUN_Health */ private $health; /** @var SUN_Wellbeing */ private $wellbeing; /** @var SUN_Bulk_Service */ private $bulk;
	/** @var SUN_Attention_Service */ private $attention; /** @var SUN_Intelligence_Service */ private $intelligence; /** @var SUN_Automation_Service */ private $automation; /** @var SUN_Routing_Service */ private $routing; /** @var SUN_Experiments_Service */ private $experiments; /** @var SUN_Trace_Service */ private $trace;
	/** @return self */ public static function instance(){if(null===self::$instance){self::$instance=new self();}return self::$instance;} private function __construct(){}

	/** @return void */
	public function boot(){
		$this->auth=new SUN_Auth();$this->registry=new SUN_Producer_Registry();$templates=new SUN_Template_Engine();$this->preferences=new SUN_Preferences($this->auth);$this->subscriptions=new SUN_Subscriptions();
		$this->attention=new SUN_Attention_Service($this->auth);$this->trace=new SUN_Trace_Service();$this->routing=new SUN_Routing_Service();$this->experiments=new SUN_Experiments_Service();$this->intelligence=new SUN_Intelligence_Service($this->attention);$this->automation=new SUN_Automation_Service($this->attention);
		$policy=new SUN_Policy_Engine($this->preferences,$this->registry,$this->subscriptions,$this->attention);$validator=new SUN_Event_Validator($this->registry);$delivery=new SUN_Delivery_Service($templates,$this->auth);
		$delivery->register_adapter(new SUN_Routed_Adapter('email',new SUN_Email_Adapter($this->auth,$templates),$this->routing));$delivery->register_adapter(new SUN_Routed_Adapter('push',new SUN_Push_Adapter(),$this->routing));$delivery->register_adapter(new SUN_Routed_Adapter('sms',new SUN_SMS_Adapter($this->auth),$this->routing));$delivery->register_adapter(new SUN_Routed_Adapter('whatsapp',null,$this->routing));$delivery->register_adapter(new SUN_Routed_Adapter('rcs',null,$this->routing));
		$this->notifications=new SUN_Notification_Service($validator,$policy,$templates,$delivery,$this->auth);$reconciliation=new SUN_Reconciliation($delivery,$this->notifications);$this->health=new SUN_Health($delivery);$this->wellbeing=new SUN_Wellbeing();$this->bulk=new SUN_Bulk_Service($this->notifications,$this->auth);$this->renderer=new SUN_Renderer($this->notifications,$this->preferences,$this->subscriptions,$this->wellbeing,$this->auth);
		$rest=new SUN_REST_Controller($this->notifications,$this->preferences,$this->subscriptions,$this->wellbeing,$delivery,$reconciliation,$this->health,$this->auth,$this->registry);$advanced_rest=new SUN_Advanced_REST($this->attention,$this->intelligence,$this->automation,$this->routing,$this->experiments,$this->trace,$this->auth);$router=new SUN_Router($this->renderer,$this->notifications,$this->auth);$admin=new SUN_Admin($this->health,$reconciliation,$this->bulk,$this->auth);$privacy=new SUN_Privacy();
		add_action('plugins_loaded',array($this,'load_textdomain'));add_action('plugins_loaded',array($this,'maybe_upgrade'),1);$this->register_cron_interval();add_action('init',array($router,'register'),5);add_action('rest_api_init',array($rest,'register_routes'));add_action('rest_api_init',array($advanced_rest,'register_routes'));add_action('wp_enqueue_scripts',array($this->renderer,'enqueue_assets'));
		add_shortcode('sabri_notification_bell',array($this->renderer,'render_bell'));add_shortcode('sabri_notifications',array($this,'center_shortcode'));add_shortcode('sabri_notification_settings',array($this->renderer,'render_settings'));add_action('sun_process_delivery_queue',array($delivery,'process_queue'));add_action('sun_reconcile_notifications',array($reconciliation,'run'));add_action('sun_expire_notifications',array($this->notifications,'expire_due'));add_action('sun_process_bulk_jobs',array($this->bulk,'process'));if(is_admin()){$admin->register();}$privacy->register();add_action('sun_file20_notification_slot',array($this,'output_bell'));add_filter('sun_file20_notification_contract',array($this,'shell_contract'));add_action('upgrader_process_complete',array($this,'maybe_upgrade'),10,2);
		add_action('sun_notification_created',array($this->attention,'on_notification_created'),10,4);add_action('sun_event_processed',array($this->automation,'on_event_processed'),10,3);add_action('sun_notification_record_engagement',array($this->attention,'record_engagement'),10,4);
	}
	/** @return void */ public function load_textdomain(){load_plugin_textdomain(SUN_TEXT_DOMAIN,false,dirname(SUN_BASENAME).'/languages');}
	/** @return void */ public function register_cron_interval(){add_filter('cron_schedules',static function($items){$items['sun_every_minute']=array('interval'=>60,'display'=>__('Every minute (File 19)','sabri-unified-notifications'));return $items;});}
	/** @param array<string,mixed> $atts Attributes. @return string */ public function center_shortcode($atts=array()){return $this->renderer->render_center(shortcode_atts(array(),$atts,'sabri_notifications'));}
	/** @return void */ public function output_bell(){echo $this->renderer->render_bell();} // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
	/** @param array<string,mixed> $contract Contract. @return array<string,mixed> */ public function shell_contract($contract){$contract['file19']=array('version'=>SUN_VERSION,'slot'=>'sun_file20_notification_slot','bell_shortcode'=>'[sabri_notification_bell]','center'=>home_url('/notifications/'),'settings'=>home_url('/settings/notifications/'),'single_bell'=>true,'intelligent_attention'=>true,'operational_gate'=>SUN_Operational_Gate::snapshot());return $contract;}
	/** @param mixed ...$unused Upgrade-hook context. @return void */ public function maybe_upgrade(...$unused){if(SUN_DB_VERSION!==get_option('sun_db_version')){SUN_Activator::install_schema();SUN_Advanced_Activator::install_schema();SUN_Advanced_Activator::seed_defaults();update_option('sun_db_version',SUN_DB_VERSION,false);update_option('sun_plugin_version',SUN_VERSION,false);SUN_Activator::schedule_events();}}
	/** @return SUN_Notification_Service */ public function notifications(){return $this->notifications;} /** @return SUN_Preferences */ public function preferences(){return $this->preferences;} /** @return SUN_Subscriptions */ public function subscriptions(){return $this->subscriptions;} /** @return SUN_Renderer */ public function renderer(){return $this->renderer;} /** @return SUN_Health */ public function health(){return $this->health;} /** @return SUN_Wellbeing */ public function wellbeing(){return $this->wellbeing;} /** @return SUN_Bulk_Service */ public function bulk(){return $this->bulk;}
	/** @return SUN_Attention_Service */ public function attention(){return $this->attention;} /** @return SUN_Intelligence_Service */ public function intelligence(){return $this->intelligence;} /** @return SUN_Automation_Service */ public function automation(){return $this->automation;} /** @return SUN_Routing_Service */ public function routing(){return $this->routing;} /** @return SUN_Experiments_Service */ public function experiments(){return $this->experiments;} /** @return SUN_Trace_Service */ public function trace(){return $this->trace;}
}
