<?php
/** WordPress privacy exporter/eraser and retention lifecycle integration. */
if ( ! defined( 'ABSPATH' ) ) { exit; }

final class SUN_Privacy {
	/** @return void */ public function register(){add_filter('wp_privacy_personal_data_exporters',array($this,'exporters'));add_filter('wp_privacy_personal_data_erasers',array($this,'erasers'));add_action('sun_privacy_retention',array($this,'retention'));}
	/** @param array<string,mixed> $exporters Exporters. @return array<string,mixed> */ public function exporters($exporters){$exporters['sabri-unified-notifications']=array('exporter_friendly_name'=>__('Sabri Notifications','sabri-unified-notifications'),'callback'=>array($this,'export'));return $exporters;}
	/** @param array<string,mixed> $erasers Erasers. @return array<string,mixed> */ public function erasers($erasers){$erasers['sabri-unified-notifications']=array('eraser_friendly_name'=>__('Sabri Notifications','sabri-unified-notifications'),'callback'=>array($this,'erase'));return $erasers;}

	/** @param string $email Email. @param int $page Page. @return array<string,mixed> */
	public function export($email,$page=1){
		global $wpdb;$user=get_user_by('email',$email);if(!$user){return array('data'=>array(),'done'=>true);}$limit=100;$page=max(1,absint($page));$offset=($page-1)*$limit;$data=array();
		$rows=$wpdb->get_results($wpdb->prepare('SELECT public_id,category,priority,title,summary,status,created_at,read_at,archived_at FROM '.SUN_Database::table('notifications').' WHERE recipient_id=%d ORDER BY id ASC LIMIT %d OFFSET %d',$user->ID,$limit,$offset),ARRAY_A);foreach($rows as $row){$data[]=$this->export_item('sabri-notifications',__('Notifications','sabri-unified-notifications'),'notification-'.$row['public_id'],$row);}
		$deliveries=$wpdb->get_results($wpdb->prepare('SELECT public_id,channel,provider,route_provider,status,attempt_count,scheduled_at,accepted_at,delivered_at,created_at,updated_at FROM '.SUN_Database::table('deliveries').' WHERE recipient_id=%d ORDER BY id ASC LIMIT %d OFFSET %d',$user->ID,$limit,$offset),ARRAY_A);foreach($deliveries as $delivery){$data[]=$this->export_item('sabri-notification-deliveries',__('Notification Delivery History','sabri-unified-notifications'),'delivery-'.$delivery['public_id'],$delivery);}
		if(1===$page){
			$prefs=$wpdb->get_results($wpdb->prepare('SELECT category,channel,enabled,digest_frequency,quiet_enabled,quiet_start,quiet_end,timezone,consent_source,consent_at,created_at,updated_at FROM '.SUN_Database::table('preferences').' WHERE user_id=%d ORDER BY id ASC',$user->ID),ARRAY_A);foreach($prefs as $index=>$pref){$data[]=$this->export_item('sabri-notification-preferences',__('Notification Preferences','sabri-unified-notifications'),'preference-'.($index+1),$pref);}
			$subs=$wpdb->get_results($wpdb->prepare('SELECT public_id,scope_type,scope_id,enabled,frequency,created_at,updated_at FROM '.SUN_Database::table('subscriptions').' WHERE user_id=%d ORDER BY scope_type,scope_id',$user->ID),ARRAY_A);foreach($subs as $sub){$data[]=$this->export_item('sabri-notification-subscriptions',__('Notification Subscriptions','sabri-unified-notifications'),'subscription-'.$sub['public_id'],$sub);}
			$devices=$wpdb->get_results($wpdb->prepare('SELECT public_id,provider,platform,status,last_seen_at,expires_at,created_at,updated_at FROM '.SUN_Database::table('devices').' WHERE user_id=%d ORDER BY id ASC',$user->ID),ARRAY_A);foreach($devices as $device){$data[]=$this->export_item('sabri-notification-devices',__('Notification Devices','sabri-unified-notifications'),'device-'.$device['public_id'],$device);}
			$profile=$wpdb->get_row($wpdb->prepare('SELECT focus_mode,essential_only,hourly_budget,daily_budget,best_time_enabled,best_time_local,ai_summary_enabled,history_days,muted_until,created_at,updated_at FROM '.SUN_Database::table('attention_profiles').' WHERE user_id=%d LIMIT 1',$user->ID),ARRAY_A);if($profile){$data[]=$this->export_item('sabri-notification-attention',__('Notification Attention Settings','sabri-unified-notifications'),'attention-profile',$profile);}
			$states=$wpdb->get_results($wpdb->prepare('SELECT n.public_id,s.pinned_at,s.snoozed_until,s.action_state,s.attention_score,s.attention_reason,s.source_label,s.source_kind,s.source_verified,s.live_revision,s.revoked_at,s.revoke_reason,s.created_at,s.updated_at FROM '.SUN_Database::table('notification_states').' s INNER JOIN '.SUN_Database::table('notifications').' n ON n.id=s.notification_id WHERE s.user_id=%d ORDER BY s.id ASC LIMIT 500',$user->ID),ARRAY_A);foreach($states as $state){$data[]=$this->export_item('sabri-notification-attention-state',__('Notification Attention State','sabri-unified-notifications'),'attention-'.$state['public_id'],$state);}
			$rules=$wpdb->get_results($wpdb->prepare('SELECT public_id,name,trigger_type,trigger_json,action_json,enabled,last_matched_at,created_at,updated_at FROM '.SUN_Database::table('notification_rules').' WHERE user_id=%d ORDER BY id ASC',$user->ID),ARRAY_A);foreach($rules as $rule){$data[]=$this->export_item('sabri-notification-rules',__('Notification Automation Rules','sabri-unified-notifications'),'rule-'.$rule['public_id'],$rule);}
			$device_profiles=$wpdb->get_results($wpdb->prepare('SELECT device_public_id,focus_mode,categories_json,channels_json,created_at,updated_at FROM '.SUN_Database::table('device_profiles').' WHERE user_id=%d ORDER BY id ASC',$user->ID),ARRAY_A);foreach($device_profiles as $device_profile){$data[]=$this->export_item('sabri-notification-device-profiles',__('Notification Device Preferences','sabri-unified-notifications'),'device-profile-'.$device_profile['device_public_id'],$device_profile);}
			$watch=$wpdb->get_results($wpdb->prepare('SELECT object_type,object_id,engagement_type,first_seen_at,last_seen_at FROM '.SUN_Database::table('watch_history').' WHERE user_id=%d ORDER BY id ASC LIMIT 1000',$user->ID),ARRAY_A);foreach($watch as $index=>$item){$data[]=$this->export_item('sabri-notification-watch-history',__('Notification Correction Watch History','sabri-unified-notifications'),'watch-'.($index+1),$item);}
		}
		return array('data'=>$data,'done'=>count($rows)<$limit&&count($deliveries)<$limit);
	}

	/** @param string $email Email. @param int $page Page. @return array<string,mixed> */
	public function erase($email,$page=1){
		global $wpdb;$user=get_user_by('email',$email);if(!$user){return array('items_removed'=>false,'items_retained'=>false,'messages'=>array(),'done'=>true);}$hold=(bool)apply_filters('sun_user_retention_hold',false,$user->ID);if($hold){return array('items_removed'=>false,'items_retained'=>true,'messages'=>array(__('Some notification records are under an approved retention hold.','sabri-unified-notifications')),'done'=>true);}
		$notes=SUN_Database::table('notifications');$devices=SUN_Database::table('devices');$prefs=SUN_Database::table('preferences');$subs=SUN_Database::table('subscriptions');$deliveries=SUN_Database::table('deliveries');$states=SUN_Database::table('notification_states');$now=SUN_Database::now();
		$wpdb->query($wpdb->prepare("UPDATE {$notes} SET recipient_id=0,status='deleted',title='',summary='',data_ciphertext=NULL,deep_link=NULL,deep_link_context=NULL,read_at=NULL,archived_at=NULL,updated_at=%s WHERE recipient_id=%d",$now,$user->ID));
		$wpdb->query($wpdb->prepare("UPDATE {$deliveries} SET recipient_id=0,provider_message_id=NULL,last_error_code=NULL,last_error_safe=NULL,updated_at=%s WHERE recipient_id=%d",$now,$user->ID));
		$wpdb->query($wpdb->prepare("UPDATE {$states} SET user_id=0,attention_reason=NULL,source_label=NULL,meta_ciphertext=NULL,pinned_at=NULL,snoozed_until=NULL,action_state='none',updated_at=%s WHERE user_id=%d",$now,$user->ID));
		foreach(array('devices','preferences','subscriptions','attention_profiles','notification_rules','device_profiles','watch_history','request_idempotency') as $logical){$wpdb->delete(SUN_Database::table($logical),array('user_id'=>$user->ID),array('%d'));}$this->scrub_legacy_event_payloads((int)$user->ID);
		do_action('sun_privacy_provider_erasure_requested',(int)$user->ID,$email);SUN_Audit::record('privacy_erasure_completed','user',hash('sha256','erased:'.$user->ID),array('purpose'=>'privacy_request','advanced_attention'=>true),0);return array('items_removed'=>true,'items_retained'=>false,'messages'=>array(),'done'=>true);
	}
	/** @return array<string,int> */ public function retention(){global$wpdb;$events=SUN_Database::table('events');$minimize_days=max(7,min(365,(int)apply_filters('sun_event_payload_retention_days',30)));$delete_days=max($minimize_days,min(730,(int)apply_filters('sun_event_row_retention_days',180)));$minimize_before=gmdate('Y-m-d H:i:s',time()-$minimize_days*DAY_IN_SECONDS);$delete_before=gmdate('Y-m-d H:i:s',time()-$delete_days*DAY_IN_SECONDS);$minimized=(int)$wpdb->query($wpdb->prepare("UPDATE {$events} SET payload_ciphertext=NULL,updated_at=%s WHERE status='processed' AND payload_ciphertext IS NOT NULL AND created_at<%s",SUN_Database::now(),$minimize_before));$deleted=(int)$wpdb->query($wpdb->prepare("DELETE e FROM {$events} e LEFT JOIN ".SUN_Database::table('notifications')." n ON n.producer=e.producer AND n.event_id=e.event_id WHERE e.created_at<%s AND n.id IS NULL",$delete_before));return array('payloads_minimized'=>max(0,$minimized),'rows_deleted'=>max(0,$deleted));}
	/** @param int $user_id User ID. @return int */ private function scrub_legacy_event_payloads($user_id){global$wpdb;$table=SUN_Database::table('events');$rows=$wpdb->get_results("SELECT id,payload_ciphertext FROM {$table} WHERE payload_ciphertext IS NOT NULL ORDER BY id DESC LIMIT 500",ARRAY_A);$changed=0;foreach((array)$rows as$row){$plain=SUN_Crypto::decrypt($row['payload_ciphertext']);if(is_wp_error($plain)){continue;}$payload=json_decode($plain,true);if(!is_array($payload)){continue;}$dirty=false;if(isset($payload['recipients'])&&is_array($payload['recipients'])){$before=count($payload['recipients']);$payload['recipients']=array_values(array_filter($payload['recipients'],static function($r)use($user_id){return absint(is_array($r)?($r['user_id']??0):$r)!==$user_id;}));$dirty=$dirty||$before!==count($payload['recipients']);}foreach(array('actor','subject')as$k){if(isset($payload[$k]['id'])&&absint($payload[$k]['id'])===$user_id){$payload[$k]=array();$dirty=true;}}if(!$dirty){continue;}$cipher=SUN_Crypto::encrypt(SUN_Database::canonical_json($payload));if(is_wp_error($cipher)){continue;}$wpdb->update($table,array('payload_ciphertext'=>$cipher,'updated_at'=>SUN_Database::now()),array('id'=>(int)$row['id']));++$changed;}return$changed;}
	/** @param string $group_id Group ID. @param string $group_label Label. @param string $item_id Item ID. @param array<string,mixed> $row Row. @return array<string,mixed> */ private function export_item($group_id,$group_label,$item_id,array $row){$data=array();foreach($row as $key=>$value){$data[]=array('name'=>ucwords(str_replace('_',' ',$key)),'value'=>(string)$value);}return array('group_id'=>$group_id,'group_label'=>$group_label,'item_id'=>$item_id,'data'=>$data);}
}
